dirpath = '../../統計分析/';
% opts = detectImportOptions(append(dirpath, 'Data_for_analysis.csv'));
% preview('D:/KIOXIA/Experiment/睡眠/統計分析/Data_for_analysis.csv', opts)
rawdataPath = append(dirpath, 'Data_for_analysis.xlsx');


%Initialize .xlsx file for saving
soSaveExcelPath = append(dirpath, 'soIndex_Summary.xlsx');
wSaveExcelPath = append(dirpath, 'W_Summary.xlsx');
stage1SaveExcelPath = append(dirpath, 'Stage1_Summary.xlsx');
psqiSaveExcelPath = append(dirpath, 'PSQI_Components_Summary.xlsx');
delete(soSaveExcelPath)
delete(wSaveExcelPath);
delete(stage1SaveExcelPath);
delete(psqiSaveExcelPath);

soSummaryExcelRange = 'A1:AL12';
soCorrExcelRange = 'A1:AL12';
psdExcelRange = 'A1:W20';
dfaExcelRange = 'A22:W41';
psqiPsdExcelRange = 'A1:AC20';
psqiDfaExcelRange = 'A22:AC41';

saveExcelSheet = {'δ_Summary', ... 
                  'θ_Summary', ...
                  'α_Summary', ...
                  'β_Summary', ...
                  'γ_Summary', ...
                  'Whole_freq_Summary'
                 };
saveDir = {'δ_index/', ... 
           'θ_index/', ...
           'α_index/', ...
           'β_index/', ...
           'γ_index/', ...
           'Whole_freq_index/'
          };
psdFigDir = 'PSD_correlation/';
dfaFigDir = 'DFA_correlation/';
wDir = {'wake-EEG_psqi/', ...
        'wake-EEG_ddfs/', ...
        'wake-EEG_mwq/', ...
        'wake-EEG_stage2-latency/'
        };
stage1Dir = {'stage1-EEG_stage2-latency/', ...
             'stage1-EEG_stage1-stage2-duration/'};

resultIndexLabel = {'ch'; ...
    'Mean'; ...
    'SD'; ...
    'Max'; ...
    'Min'; ...
    'Stage1 r'; ...
    'Stage1 p'; ...
    'Stage2 r'; ...
    'Stage2 p'};

wC = readcell(rawdataPath, 'Sheet', 'W_Data');
stage1C = readcell(rawdataPath, 'Sheet', 'Stage1_Data');

%Extract vals from the psqi to the end of dfa scaling exponent
ageCol = 3;
wM = cell2mat(wC(2:end, ageCol:end));
stage1M = cell2mat(stage1C(2:end, ageCol:end));
varname = wC(1, ageCol:end);
fbandNum = 6;
chNum = 19;
psdFir = 20;
psdEnd = psdFir+(chNum-1);
dfaFir = psdEnd+1;
dfaEnd = dfaFir+(chNum-1);
indexLen = dfaEnd - psdFir + 1;

%age
age = wM(:, 1);
%sex
sex = wM(:, 2);
%covariates for partial correlation
covar = [age sex];

%PSQI
psqi = wM(:, 4:13);
psqiVar = wC(1, 6:15);

%DDFS
ddfs = wM(:, 14);
%MWQ
mwq = wM(:, 15);

%Stage2 Latency
s2_lat = wM(:, 16);
%Stage1 Latency
w_dur = wM(:, 18);
%Stage1-Stage2 duration time
% s1_s2_duration = wM(:, 17);
%Sleep Stage Matrix
% SleepMat = horzcat(w_dur, s2_lat, s1_s2_duration);

%mat(chCol+solCol, ~, fbandNum)
wPsdR = zeros(chNum+2, chNum+2, fbandNum);
wPsdP = zeros(chNum+2, chNum+2, fbandNum);
wDfaR = zeros(chNum+2, chNum+2, fbandNum);
wDfaP = zeros(chNum+2, chNum+2, fbandNum);

stage1PsdR = zeros(chNum+2, chNum+2, fbandNum);
stage1PsdP = zeros(chNum+2, chNum+2, fbandNum);
stage1DfaR = zeros(chNum+2, chNum+2, fbandNum);
stage1DfaP = zeros(chNum+2, chNum+2, fbandNum);

wPsdSummary = [];
wDfaSummary = [];
stage1PsdSummary = [];
stage1DfaSummary = [];

%Setting so var's name
soVarname = wC(1, [7 8 13:16])';
psqi = psqi(:, [2 3 8]);
%Subjective/Objective Indice
%Summary Statistics
    soVar = [psqi ddfs mwq s2_lat];
    [soCorr, soMean, soStd, soMax, soMin] = ...
        calcSummary(soVar, covar);
%Manual p correction
   soVarSize = size(soVar, 2);

% for f = 1
for f = 6
    disp(saveDir(f))

    %Initialize Stage W EEG directories for saving.
    for d = 1:length(wDir)
        wPsdSaveDir(d) = append(dirpath, saveDir(f), psdFigDir, wDir(d));
        wDfaSaveDir(d) = append(dirpath, saveDir(f), dfaFigDir, wDir(d));

    end

    %Initialize Stage 1 EEG directories for saving.
%     for d = 1:length(stage1Dir)
%         stage1PsdSaveDir(d) = append(dirpath, saveDir(f), psdFigDir, stage1Dir(d));
%         stage1DfaSaveDir(d) = append(dirpath, saveDir(f), dfaFigDir, stage1Dir(d));
% 
%     end

    %Extract each fband's data

    %Extract All channel's name and data
    psdLen = psdFir+indexLen*(f-1):psdEnd+indexLen*(f-1);
    dfaLen = dfaFir+indexLen*(f-1):dfaEnd+indexLen*(f-1);
    psdVarname = varname(psdLen)';
    dfaVarname = varname(dfaLen)';
%     
    %Create EEG index matrix from each sleep stage.
    wPsdMat = wM(:, psdLen);
    wDfaMat = wM(:, dfaLen);
%     stage1PsdMat = stage1M(:, psdLen);
%     stage1DfaMat = stage1M(:, dfaLen);

    %Extract Bilateral Channels
%     psdVarname = vertcat(psdVarname(1:4), psdVarname(12:13), psdVarname(15:16));
%     dfaVarname = vertcat(dfaVarname(1:4), dfaVarname(12:13), dfaVarname(15:16));
%     wPsdMat = [wPsdMat(:, 1:4) wPsdMat(:, 12:13) wPsdMat(:, 15:16)];
%     wDfaMat = [wDfaMat(:, 1:4) wDfaMat(:, 12:13) wDfaMat(:, 15:16)];

    %Extract fronto-central Channels
%     psdVarname = vertcat(psdVarname(1:6), psdVarname(12:13));
%     dfaVarname = vertcat(dfaVarname(1:6), dfaVarname(12:13));
%     wPsdMat = [wPsdMat(:, 1:6) wPsdMat(:, 12:13)];
%     wDfaMat = [wDfaMat(:, 1:6) wDfaMat(:, 12:13)];

    %Extract midline Channels
%     psdVarname = vertcat(psdVarname(7), psdVarname(14), psdVarname(17));
%     dfaVarname = vertcat(dfaVarname(7), dfaVarname(14), dfaVarname(17));
%     wPsdMat = [wPsdMat(:, 7) wPsdMat(:, 14) wPsdMat(:, 17)];
%     wDfaMat = [wDfaMat(:, 7) wDfaMat(:, 14) wDfaMat(:, 17)];

    %Extract C3 C4 Cz
    psdVarname = psdVarname(12:13);
    dfaVarname = dfaVarname(12:13);
    wPsdMat = [wPsdMat(:, 12:13)];
    wDfaMat = [wDfaMat(:, 12:13)];

    %Cz
%     psdVarname = psdVarname(14);
%     dfaVarname = dfaVarname(14);
%     wPsdMat = [wPsdMat(:, end-5)];
%     wDfaMat = [wDfaMat(:, end-5)];

    %-------Execute statistic analysis------- 

    %WAKE PERIOD EEG 
    %Summary Statistics
    [wPsdStage1Corr, wPsdMean, wPsdStd, wPsdMax, wPsdMin] = ...
        calcSummary(wPsdMat, w_dur, covar);
    [wDfaStage1Corr, wDfaMean, wDfaStd, wDfaMax, wDfaMin] = ...
        calcSummary(wDfaMat, w_dur, covar);
    %PSQI Correlation
    [wPsdPsqiCorr] = calcSummary(wPsdMat, psqi, covar);
    [wDfaPsqiCorr] = calcSummary(wDfaMat, psqi, covar);
    %DDFS Correlation
    [wPsdDdfsCorr] = calcSummary(wPsdMat, ddfs, covar);
    [wDfaDdfsCorr] = calcSummary(wDfaMat, ddfs, covar);
    %MWQ Correlation
    [wPsdMwqCorr] = calcSummary(wPsdMat, mwq, covar);
    [wDfaMwqCorr] = calcSummary(wDfaMat, mwq, covar);
    %S2_lat Correlation
    [wPsdStage2Corr] = calcSummary(wPsdMat, s2_lat, covar);
    [wDfaStage2Corr] = calcSummary(wDfaMat, s2_lat, covar);
    %Stage1_Dur Correlation
%     [wPsdDurationCorr] = calcSummary(wPsdMat, s1_s2_duration, covar);
%     [wDfaDurationCorr] = calcSummary(wDfaMat, s1_s2_duration, covar);
    %Create Entire Correlation Matrix
    wPsdCorrs = horzcat(wPsdPsqiCorr(:, 1:2), ...
                        wPsdDdfsCorr(:, 1:2), ...
                        wPsdMwqCorr(:, 1:2), ...
                        wPsdStage2Corr(:, 1:2));
    wDfaCorrs = horzcat(wDfaPsqiCorr(:, 1:2), ...
                        wDfaDdfsCorr(:, 1:2), ...
                        wDfaMwqCorr(:, 1:2), ...
                        wDfaStage2Corr(:, 1:2));

%     %STAGE1 PERIOD EEG
%     %PSQI Correlation
%     [stage1PsdPsqiCorr] = calcSummary(stage1PsdMat, psqi, covar);
%     [stage1DfaPsqiCorr] = calcSummary(stage1DfaMat, psqi, covar);
%     %DDFS Correlation
%     [stage1PsdDdfsCorr] = calcSummary(stage1PsdMat, ddfs, covar);
%     [stage1DfaDdfsCorr] = calcSummary(stage1DfaMat, ddfs, covar);
%     %MWQ Correlation
%     [stage1PsdMwqCorr] = calcSummary(stage1PsdMat, mwq, covar);
%     [stage1DfaMwqCorr] = calcSummary(stage1DfaMat, mwq, covar);
%     %S2_lat Correlation
%     [stage1PsdStage2Corr, stage1PsdMean, stage1PsdStd, stage1PsdMax, stage1PsdMin] = ...
%         calcSummary(stage1PsdMat, s2_lat, covar);
%     [stage1DfaStage2Corr, stage1DfaMean, stage1DfaStd, stage1DfaMax, stage1DfaMin] = ...
%         calcSummary(stage1DfaMat, s2_lat, covar);
%     %Stage1_Dur Correlation
%     [stage1PsdDurationCorr] = calcSummary(stage1PsdMat, s1_s2_duration, covar);
%     [stage1DfaDurationCorr] = calcSummary(stage1DfaMat, s1_s2_duration, covar);
%     %Create Entire Correlation Matrix
%     stage1PsdCorrs = horzcat(stage1PsdStage2Corr, stage1PsdDurationCorr);
%     stage1DfaCorrs = horzcat(stage1DfaStage2Corr, stage1DfaDurationCorr);

    %---------Create Summary Table of each period---------
    soSummaryTable = table(soVarname, ...
                                 soMean, ...
                                 soStd, ...
                                 soMax, ...
                                 soMin, ...
                                 soCorr);
%     questionCorrTable = table(psqiCorr, ...
%                               ddfsCorr, ...
%                               mwqCorr, ...
%                               latCorr);
    wPsdSummaryTable = table(psdVarname, ...
                            wPsdMean, ...
                            wPsdStd, ...
                            wPsdMax, ...
                            wPsdMin, ...
                            wPsdDdfsCorr, ...
                            wPsdMwqCorr, ...
                            wPsdStage2Corr);
    wDfaSummaryTable = table(dfaVarname, ...
                            wDfaMean, ...
                            wDfaStd, ...
                            wDfaMax, ...
                            wDfaMin, ...
                            wDfaDdfsCorr, ...
                            wDfaMwqCorr, ...
                            wDfaStage2Corr);

    psqiPSDTable = table(psdVarname,wPsdPsqiCorr);
    psqiDfaTable = table(dfaVarname, wDfaPsqiCorr);
%     stage1PsdSummaryTable = table(psdVarname, ...
%                                   stage1PsdMean, ...
%                                   stage1PsdStd, ...
%                                   stage1PsdMax, ...
%                                   stage1PsdMin, ...
%                                   stage1PsdPsqiCorr, ...
%                                   stage1PsdDdfsCorr, ...
%                                   stage1PsdMwqCorr, ...
%                                   stage1PsdDurationCorr, ...
%                                   stage1PsdStage2Corr);
%     stage1DfaSummaryTable = table(dfaVarname, ...
%                                   stage1DfaMean, ...
%                                   stage1DfaStd, ...
%                                   stage1DfaMax, ...
%                                   stage1DfaMin, ...,
%                                   stage1DfaPsqiCorr, ...
%                                   stage1DfaDdfsCorr, ...
%                                   stage1DfaMwqCorr, ...
%                                   stage1DfaDurationCorr, ...
%                                   stage1DfaStage2Corr);
    
    %---------Create Excel File for Results------------
    writetable(soSummaryTable, ...
               soSaveExcelPath, ...
               'Sheet', 'Summary', ...
               'Range', soSummaryExcelRange);
    writetable(wPsdSummaryTable, ...
               wSaveExcelPath, ...
               'Sheet', char(saveExcelSheet(f)), ...
               'Range', psdExcelRange)
    writetable(wDfaSummaryTable, ...
               wSaveExcelPath, ...
               'Sheet', char(saveExcelSheet(f)), ...
               'Range', dfaExcelRange)

    writetable(psqiPSDTable, ...
               psqiSaveExcelPath, ...
               'Sheet', char(saveExcelSheet(f)), ...
               'Range', psqiPsdExcelRange)
    writetable(psqiDfaTable, ...
               psqiSaveExcelPath, ...
               'Sheet', char(saveExcelSheet(f)), ...
               'Range', psqiDfaExcelRange)
%     writetable(stage1PsdSummaryTable, ...
%                stage1SaveExcelPath, ...
%                'Sheet', char(saveExcelSheet(f)), ...
%                'Range', psdExcelRange)
%     writetable(stage1DfaSummaryTable, ...
%                stage1SaveExcelPath, ...
%                'Sheet', char(saveExcelSheet(f)), ...
%                'Range', dfaExcelRange)
    

% %---------------------Scatter definition---------------------------------
% %     %Scatter parameters
%     wPsdXLim = psdLim([wPsdMin, wPsdMax]);
%     wDfaXLim = dfaLim([wDfaMin, wDfaMax]);
% %     
% %     stage1PsdXLim = psdLim([stage1PsdMin, stage1PsdMax]);
% %     stage1DfaXLim = dfaLim([stage1DfaMin, stage1DfaMax]);
% 
% %     psdXLim = psdLim([wPsdMin, wPsdMax], [stage1PsdMin, stage1PsdMax]);
% %     dfaXLim = dfaLim([wDfaMin wDfaMax], [stage1DfaMin stage1DfaMax]);
%     psdXLim = psdLim([wPsdMin, wPsdMax]);
%     dfaXLim = dfaLim([wDfaMin wDfaMax]);
%     yLim = [0, max(psqi(:, 3))+1; ...
%             0, 48; ...
%             0, 30; ...
%             latLim([0 max(s2_lat)])];
%     yTicksInt = [2, 8, 6, 5];
%     
%     %Make Scatters of Stage W EEG
%     for ch = 1:length(psdVarname)
%         for d = 1:length(wDir)
%             xPsdLabel = append(char(psdVarname(ch)), ' on StageW');
%             xDfaLabel = append(char(dfaVarname(ch)), ' on StageW');
%             psdSavePath = append(wPsdSaveDir(d), psdVarname(ch), '.png');
%             dfaSavePath = append(wDfaSaveDir(d), dfaVarname(ch), '.png');
%             y = soVar(:, d);
% %             lat = SleepMat(:, d+1);
%             wPsdCorr = wPsdCorrs(:, 2*d-1:2*d);
%             wDfaCorr = wDfaCorrs(:, 2*d-1:2*d);
%             wPsdXTicks = wPsdXLim(1):0.5:wPsdXLim(2);
%             wDfaXTicks = wDfaXLim(1):0.1:wDfaXLim(2);
%             yTicks = yLim(d, 1):yTicksInt(d):yLim(d, 2);
% %             corrScatter(wPsdMat(:, ch), lat, ...
% %                         xPsdLabel, soVarname(d), ...
% %                         psdXLim, yLim(d, :), ...
% %                         wPsdCorr(ch, 1), wPsdCorr(ch, 2), ...
% %                         psdSavePath, (psdXLim(1):0.5:psdXLim(2)));
% % 
% %             corrScatter(wDfaMat(:, ch), lat, ...
% %                         xDfaLabel, soVarname(d), ...
% %                         dfaXLim, yLim(d, :), ...
% %                         wDfaCorr(ch, 1), wDfaCorr(ch, 2), ...
% %                         dfaSavePath, (dfaXLim(1):0.1:dfaXLim(2)));
%             
%             %Ticks versions
%             corrScatter(wPsdMat(:, ch), y, ...
%                         xPsdLabel, soVarname(d), ...
%                         wPsdXLim, yLim(d, :), ...
%                         wPsdCorr(ch, 1), wPsdCorr(ch, 2), ...
%                         psdSavePath, ...
%                         wPsdXTicks, yTicks);
% 
%             corrScatter(wDfaMat(:, ch), y, ...
%                         xDfaLabel, soVarname(d), ...
%                         wDfaXLim, yLim(d, :), ...
%                         wDfaCorr(ch, 1), wDfaCorr(ch, 2), ...
%                         dfaSavePath, ...
%                         wDfaXTicks, yTicks);
%         end
%         
% % %         for d = 1:length(stage1Dir)
% % %             %Make Scatters of Stage 1 EEG
% % %             xPsdLabel = append(char(psdVarname(ch)), ' on Stage1');
% % %             xDfaLabel = append(char(dfaVarname(ch)), ' on Stage1');
% % %             stage1soVarname = wC(1, 11:12);
% % %             psdSavePath = append(stage1PsdSaveDir{d}, psdVarname(ch), '.png');
% % %             dfaSavePath = append(stage1DfaSaveDir{d}, dfaVarname(ch), '.png');
% % %             lat = SleepMat(:, d+1);
% % %             stage1PsdCorr = stage1PsdCorrs(:, 2*d-1:2*d);
% % %             stage1DfaCorr = stage1DfaCorrs(:, 2*d-1:2*d);
% % % %              corrScatter(stage1PsdMat(:, ch), lat, ...
% % % %                 xPsdLabel, soVarname(d), ...
% % % %                 psdXLim, yLim, ...
% % % %                 stage1PsdStage2Corr(ch, 1), stage1PsdStage2Corr(ch, 2), ...
% % % %                 psdSavePath, (psdXLim(1):0.5:psdXLim(2)));
% % % % 
% % % %             corrScatter(stage1DfaMat(:, ch), lat, ...
% % % %                 xDfaLabel, soVarname(d), ...
% % % %                 dfaXLim, yLim, ...
% % % %                 stage1DfaCorr(ch, 1), stage1DfaCorr(ch, 2), ...
% % % %                 dfaSavePath, (dfaXLim(1):0.1:dfaXLim(2)));
% % %             corrScatter(stage1PsdMat(:, ch), lat, ...
% % %                 xPsdLabel, stage1soVarname(d), ...
% % %                 stage1PsdXLim, latLim([0 max(lat)]), ...
% % %                 stage1PsdStage2Corr(ch, 1), stage1PsdStage2Corr(ch, 2), ...
% % %                 psdSavePath, (stage1PsdXLim(1):0.5:stage1PsdXLim(2)));
% % % 
% % %             corrScatter(stage1DfaMat(:, ch), lat, ...
% % %                 xDfaLabel, stage1soVarname(d), ...
% % %                 stage1DfaXLim, latLim([0 max(lat)]), ...
% % %                 stage1DfaCorr(ch, 1), stage1DfaCorr(ch, 2), ...
% % %                 dfaSavePath, (stage1DfaXLim(1):0.1:stage1DfaXLim(2)));
% % %         end
%     end
end